# src/portfolio_mapper/config/llm_config.py

# Copyright (c) Adrian Robinson 2025
# This software is dual-licensed under the MIT License (for NHS use only)
# and a Commercial License (for other use).
# For commercial licensing inquiries, please contact adrian.j.robinson@gmail.com

app:
  # Set to true to print detailed debugging information
  # (like prompts and raw AI responses) to the console.
  debug_mode: false
  min_reflection_length: 100

gemini:
  # The specific model to use for the analysis.
  # e.g., "gemini-1.5-pro-latest" or "gemini-1.5-flash-latest"
  model_name: "gemini-1.5-flash-latest"

  # Generation parameters to control the creativity and style of the output.
  # Uncomment and adjust these values to experiment.
  generation_config:
    temperature: 0.5
    # top_p: 0.95
    # top_k: 40

  # Safety settings to control content filtering.
  safety_settings:
    - { category: "HARM_CATEGORY_HARASSMENT", threshold: "BLOCK_NONE" }
    - { category: "HARM_CATEGORY_HATE_SPEECH", threshold: "BLOCK_NONE" }
    - { category: "HARM_CATEGORY_SEXUALLY_EXPLICIT", threshold: "BLOCK_NONE" }
    - { category: "HARM_CATEGORY_DANGEROUS_CONTENT", threshold: "BLOCK_NONE" }